### ISSUE TITLE
[Full App Display] Playlists, Top Ribbon, and Bottom controls still show

### ISSUE THREAD

**Issue by Kvan7** [huhridge/huh-spicetify-extensions#85]
**Describe the bug**
When going to full screen the navbar column, controls, and top ribbon are still displayed. They are none intractable, so the FAD is likely on top of them, although the background album cover for FAD is not displaying and is instead using the theme's color. FAD controls are fully functional and right click still brings up the options. This appears to be related to #81, I did uninstall from the marketplace and installed from this repo directly in case the fix for #81 hadn't been pushed to marketplace. 

Don't know how to show the background image, but setting the navbar, topbar, and now-playing to none does make them go away, so this should likely just be a css issue. 

**To Reproduce**
In theory just install and hit the FAD button

**Expected behavior**
The default elements of the Spotify ui should be hidden or none.

**Console Errors**
No errors on hitting FAD except forced.
These on startup but likely other extensions:
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/71402892/e0c364da-761a-4fb3-9a03-2280a255afd8)

**Screenshots**
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/71402892/e64ee109-239e-4992-8867-8f59aae99d6a)

**Desktop (please complete the following information):**
Spotify for Windows (64 bit)
1.2.25.1011.g0348b2ea
Spicetify v2.28.0
xpui_2023-11-20_1700498575257_0348b2e
cef_118.7.1+g99817d2+chromium-118.0.5993.119

**Additional context**

**Comment by huhridge** [comment]
what mode are you using? i.e. are you using the album cover, or the background color mode?

**Comment by BaigHack3rss** [comment]
I fixed this by just tinkering in the right click menu. I didn't have to open any code I think I just switched to color mode then back changed the color and then went back to album art.

**Comment by Kvan7** [comment]
Interesting, it was set to album cover, but changing it to another background option and back did fix it as well. Not sure why it was occurring then. Stayed fixed after restarting the program too. Probably has something to do with when spotify or spicetify updated. 

Can probably close unless you want more information. Still really confused on how it happened and why it didn't fix itself with a reinstall

**Comment by BaigHack3rss** [comment]
> Interesting, it was set to album cover, but changing it to another background option and back did fix it as well. Not sure why it was occurring then. Stayed fixed after restarting the program too. Probably has something to do with when spotify or spicetify updated.
> 
> Can probably close unless you want more information. Still really confused on how it happened and why it didn't fix itself with a reinstall

I agree with you when you say that it must of been from a spicetify update. I forgot to mention that it happened after a spicetify update so I think it just glitched out or smthin

**Comment by huhridge** [comment]
ok closing this for now!
